require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

platform :ios, '10.0'

target 'flight_briefing' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'flight_briefingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'flight_briefing-tvOS' do
  # Pods for flight_briefing-tvOS

  target 'flight_briefing-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
